name: release-build

on:
  release:
    types:
      - published

jobs:
  build_mcrelay:
    name: Build Minecraft Relay Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Upgrade environment
        run: |
          sudo apt update
          sudo apt upgrade -y
      - name: Install toolchain
        run: |
          sudo apt install -y gcc gcc-aarch64-linux-gnu gcc-arm-linux-gnueabihf gcc-powerpc64le-linux-gnu gcc-riscv64-linux-gnu gcc-s390x-linux-gnu
          sudo mv /etc/apt/sources.list /etc/apt/sources.list.d/main.list
          sudo touch /etc/apt/sources.list
          sudo sed -i '/^$/d;/^#/d;s/deb/deb [arch=amd64]/g' /etc/apt/sources.list.d/main.list
          sudo cp /etc/apt/sources.list.d/main.list /etc/apt/sources.list.d/port.list
          sudo sed -i 's/arch=amd64/arch=arm64,armhf,ppc64el,riscv64,s390x/g;s/archive/ports/g;s/security\./security.ports./g;s/\/ubuntu/\/ubuntu-ports/g' /etc/apt/sources.list.d/port.list
          sudo dpkg --add-architecture arm64
          sudo dpkg --add-architecture armhf
          sudo dpkg --add-architecture ppc64el
          sudo dpkg --add-architecture riscv64
          sudo dpkg --add-architecture s390x
          sudo apt update
          sudo apt install -y libcjson-dev:amd64 libcjson-dev:arm64 libcjson-dev:armhf libcjson-dev:ppc64el libcjson-dev:riscv64 libcjson-dev:s390x
      - name: Build amd64
        run: |
          mkdir build-amd64
          cd build-amd64
          cmake -DCMAKE_C_COMPILER=`which gcc` -DEXEC_SUFFIX="-amd64" ..
          make
          cd ..
      - name: Build arm64
        run: |
          mkdir build-arm64
          cd build-arm64
          cmake -DCMAKE_C_COMPILER=`which aarch64-linux-gnu-gcc` -DEXEC_SUFFIX="-arm64" ..
          make
          cd ..
      - name: Build armhf
        run: |
          mkdir build-armhf
          cd build-armhf
          cmake -DCMAKE_C_COMPILER=`which arm-linux-gnueabihf-gcc` -DEXEC_SUFFIX="-armhf" ..
          make
          cd ..
      - name: Build ppc64el
        run: |
          mkdir build-ppc64el
          cd build-ppc64el
          cmake -DCMAKE_C_COMPILER=`which powerpc64le-linux-gnu-gcc` -DEXEC_SUFFIX="-ppc64el" ..
          make
          cd ..
      - name: Build riscv64
        run: |
          mkdir build-riscv64
          cd build-riscv64
          cmake -DCMAKE_C_COMPILER=`which riscv64-linux-gnu-gcc` -DEXEC_SUFFIX="-riscv64" ..
          make
          cd ..
      - name: Build s390x
        run: |
          mkdir build-s390x
          cd build-s390x
          cmake -DCMAKE_C_COMPILER=`which s390x-linux-gnu-gcc` -DEXEC_SUFFIX="-s390x" ..
          make
          cd ..
      - name: Post build
          mkdir build
          cd build
          cp ../build-amd64/mcrelay-amd64 .
          cp ../build-arm64/mcrelay-arm64 .
          cp ../build-armhf/mcrelay-armhf .
          cp ../build-ppc64el/mcrelay-ppc64el .
          cp ../build-riscv64/mcrelay-riscv64 .
          cp ../build-s390x/mcrelay-s390x .
      - name: Upload artifacts
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'build/mcrelay-*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
